# Generated by Django 4.2.7 on 2024-07-12 10:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='заголовок поста')),
                ('content', models.TextField(blank=True, default='No content', validators=[django.core.validators.MinLengthValidator(3)], verbose_name='содержимое поста')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания поста')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='дата и время изменения поста')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор поста')),
            ],
            options={
                'verbose_name': 'пост пользователя',
                'verbose_name_plural': 'посты пользователей',
                'ordering': ['autor'],
            },
        ),
    ]
