# Generated by Django 4.2.7 on 2024-07-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['author'], 'verbose_name': 'пост пользователя', 'verbose_name_plural': 'посты пользователей'},
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='autor',
            new_name='author',
        ),
    ]
